services:
  emqx:
    image: emqx/emqx-enterprise:6.2.0
    container_name: emqx
    environment: 
      EMQX_NODE_NAME: emqx@node1.emqx.local
    ports:
      - "1883:1883"
      - "8883:8883"
      - "8083:8083"
      - "8084:8084"
      - "127.0.0.1:18083:18083"
    volumes:
      - ./emqx/data:/opt/emqx/data
      - ./emqx/log:/opt/emqx/log
    restart: unless-stopped
            